---
- name: Play book for useradd Demo
  hosts: all
  become: yes
  gather_facts: no
  remote_user: ansible
  tasks:
   - name: Task to create a new user
     user:
      name: auser01
      password: "{{ 'test123' | password_hash('sha512') }}"
      uid: 8899
      home: /home/auser01
      shell: /bin/bash
      comment: Created by Ansible Playbook
      state: present
...
#End of play
