---
- name: demonstrate using fetch module to download a file from remote server
  hosts: 192.168.1.82
  become: true
  remote_user: ansible
  tasks:
   - name: fetch /var/log/messages file
     fetch:
      src: /var/log/messages
      dest: /tmp/{{ansible_hostname}}/
      flat: yes
      #flat: yes this downloads only the file name
      #flat: no this creates a directory with hostname and an absolute path of the file also downloaded
...