---
- name: Play to demonstrate unarchive module
  hosts: 192.168.1.82
  become: true
  remote_user: ansible
  tasks:
   - name: play to unarchive a archived file
     unarchive:
       src: /home/ansible/my.tar
       dest: /home/ansible/
       remote_src: yes
...