---
- name: Play to create a cron job that runs every saturday 8:30pm
  hosts: all
  become: true
  remote_user: ansible
  tasks:
   - name: task to create a cron job
     cron:
       name: Myfirstcron
       minute: 30
       hour: 20
       day: "*"
       month: "*"
       weekday: "6" #saturday
       job: "/usr/bin/df -h >>/tmp/df.out"
       #state: absent
...