---
- name: Play to demonstrate iterative statement in ansible
  hosts: localhost
  remote_user: ansible
  gather_facts: no
  become: true
  tasks:
  - name: Task to repeat for 5 times
    debug:
      msg: "Hello ..... Its me .... Ansible ...{{item}}"
   # loop: [1,2,3,4,5]
    loop:
     - 1
     - 2
     - 3
     - 4
     - 5
...