---
- name: Play to demonstrate hostname change
  hosts: 192.168.1.82
  become: true
  remote_user: ansible
  tasks:
   - name: play to change hostname
     hostname:
      name: siva.alclabs.in #change hostname permanently
...