---
- name: Play to demonstrate uri module
  hosts: localhost
  remote_user: ansible
  become: true
  gather_facts: yes
  tasks:
   - name: Task to demonstrate uri module
     uri:
      url: http://192.168.1.82/index.html
      return_content: yes
     register: out
     ignore_errors: yes
   - name: Print the register variable
     debug:
      var: out #"{{out.status}}"
...