---
- name: play to demonstrate archive module. ie tar and gzip
  hosts: 192.168.1.82
  become: true
  remote_user: ansible
  tasks:
   - name: task to archive the given directory
     archive:
       path:
        - /etc/*
        - /var/*
       format: gz # compreeses the archive
       dest: my.tar.gz #by default it will be store in ansible home directory
...