---
- name: Play book to remove user
  hosts: all
  become: yes
  gather_facts: no
  remote_user: ansible
  tasks:
   - name: Task to delete a user
     user:
      name: auser01
      remove: yes #delete home directory
      state: absent
...
#End of play

