---
- name: play to reboot managed node(s)
  hosts: 192.168.1.83
  gather_facts: no
  become: true
  remote_user: ansible
  tasks:
   - name: task to reboot managed node(s)
     reboot:
       msg: "Reboot Initiated by ansible.. Please wait for some time and try to login...."
...