---
- name: Demonstrate variables
  hosts: localhost
  become: true
  remote_user: ansible
  vars_files:
   - vars/prod_user.yml
  vars:
    u1_name: oradm
  tasks:
   - name: Include variables
     include_vars: vars/dev_user.yml
   - name: Task to check variable sequence
     debug:
       msg: "{{u1_name}}"
       # The order of the value choose from variable is command line -e variable=value 
       #then include_vars in the tasks then global finally local variable
...