---
- name: Play to demonstrate rsync
  hosts: 192.168.1.82
  become: true
  remote_user: ansible
  vars:
   destin_dir: /home/ansible/day3
   source_dir: /trainer_plays
  tasks:
   - name: Synchronize {{source_dir}} and {{destin_dir}} using synchronize module
     synchronize:
      src: "{{source_dir}}"
      dest: "{{destin_dir}}"
      compress: yes
      archive: yes
      recursive: yes
      mode: pull
...