---
- name: Demonstarate replace module in ansible
  hosts: 192.168.1.82
  become: true
  remote_user: ansible
  tasks:
   - name: Task to replace the text using replace module
     replace:
       path: /etc/iscsi/initiatorname.iscsi
       regexp: iqn.2024-06.in.myclass.siva:receive1
       replace: iqn.2024-07.in.myclass.sivakumar:iamreplaced
       backup: yes
...