---
#ansible-vault create user_sec.yml: To create ansible vault file
#ansible-vault view user_sec.yml: To view the contents of the file
#ansible-vault edit user_sec.yml: to edit the file
#ansible-vault rekey user_sec.yml: to change vault password
#ansible-vault encrypt flatfile.yml --output=user_sec.yml : create an encrypted vault from normal file
#ansible-vault decrypt user_sec.yml --output=Normalfile.yml : To create decrypted file from encrypted vault
#ansible-playbook --ask-vault-pass sec_play1.yml: to run play which is using vault feature
# you can put password in a file and use to run the playbook. Ex: vi pass.txt and type vault password.
#ansible-playbook --vault-password-file=pass.txt sec_play1.yml: run play without providing password interactivly
#play using ansible vault to set password for crearted users
- name: create users and set password through ansible vault
  hosts: localhost
  become: true
  vars_files:
   - mypass.yml
  tasks:
   - name: create users
     user:
      name: "{{item}}"
      password: "{{pass|password_hash('sha512')}}" #This variable data comes from ansible vault
      update_password: on_create
      state: present
     loop:
      - rocky
      - jocky
      - micky
      - locky
...