---
- name: Play to create user and group and add created group as secondary group 
  hosts: 192.168.1.82
  become: true
  remote_user: ansible
  tasks:
   - name: create a user
     user:
      name: nancy
      state: present
   - name: create a group
     group:
       name: puppy
       state: present
   - name: Add the group as secondary group
     user:
       name: nancy
       groups: puppy
       append: yes
...