---
- name: Create a user and add ssh public key to user's authorized keys
  hosts: all
  become: true
  remote_user: ansible
  tasks:
   - name: Add a user
     user:
       name: asian
       password: "{{ 'test123' | password_hash('sha512')}}"
       state: present
   - name: Task to add SSH keys to the user
     authorized_key:
      user: asian
      state: present
      key: "{{lookup('file', '/home/ansible/id_rsa.pub')}}" 
...