---
- name: Play to demonstrate register variables
  hosts: all
  become: yes
  remote_user: ansible
  tasks:
   - name: task to start web server
     service:
      name: httpd
      state: restarted
     register: vname1
   - name: debug module to print register variable
     debug:
       #var: vname1
       msg: "The service name is: {{vname1.name}} and state is {{vname1.state}}"
       #The status of the program can be seen by using -vvv at the end of the command
...